{{- if .Values.ingress.enabled -}}
  {{- $serviceName := include "raccoon.fullname" . -}}
  {{- $ingressPath := .Values.ingress.path -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata: 
  name: {{ template "raccoon.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: 
  {{- if .Values.labels }}
      {{- toYaml .Values.labels | trim | nindent 4 }}
    {{- end }}
    run: {{ .Release.Name }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end}}
spec:
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $.Values.raccoon.config.SERVER_WEBSOCKET_PORT }}
    {{- end -}}
  {{- if index .Values.ingress.tls.enabled }}
  tls:
    - secretName: {{ .Values.ingress.tls.secretName }}
      hosts:
    {{- range $host := .Values.ingress.hosts }}
      - {{ $host }}
    {{- end -}}
{{- end -}}
{{- end -}}
